language: ruby
cache: bundler
rvm:
  - 2.3
  - 2.4
  - 2.5
  - jruby
before_install:
  - gem install bundler

deploy:
  provider: rubygems
  on:
    tags: true
  api_key:
    secure: wz1WG7qnA8x1DmMgpx4B9nIu0LPHXy1iSom7xcfv+AG4DgLvIv6CBAgMS5kaWdFB3IHdJSePGa1KC9xQ1NjQneFmVJhNbVtYVThDWckSCQoEKLDrnCZ8S2Ftwy3AqznyGg4ARITS7Ft/AVNaRQRCOk8onuUjkHVrvWc/vZv8c3Qz0nS9yzHLBov6PHjbJQU5Lmjmy1ODVTlu/kN11s1SUbN51fWoOuXDAxllp0ojSidZy2Zfpfxxtkm48i8CzGVUFIRpIpM4B9EB6Hr4UEvVBgU+G9aOAF5Pb7PS+xXgslHxlAdK9gdI6pHv0luTTHnRGn2BPBkrUc8qFRCrYkOD2hKFcUqEXSpnxBAeNmiD2pzIYTPFxnfGaAg4PInjfU08X2CVWqqL/VgYLLHDWkG+uNKCnX3cxtJmrQsNz3HK+F3i8WRNGiOKHXhUV0mz0C/y1ojCqMvxHOYgwECyLGsXo5uKmaK+BaPeMKr4mV+UKKRI3v7FIuWS9EDtKHxB0Lya3NKroNpuKrWQCruFQcLLXZX1gWGO8CYlAlNbJ4OkDGekl/wOzK0mDhx4tu/Ejd3MEs226F8gwQ87GuTeUWGHY74xk8HiULfbo4jjSx5ONFtRYNgrSxyx2ZLUCS6gcn0MKEt2gTC38xEcbWaD3Lw81qLV98zwUXWe+we6p9xWmKQ=
