version: 2

jobs:
  test-2.3:
    docker:
      - image: circleci/ruby:2.3
    steps:
      - checkout
      - run:
          name: Prepare Ruby environment
          command: |
            ruby --version
            echo "gem `gem --version`"
            gem update --system
            gem install bundler
            bundle install
      - run: rake test
  test-2.4:
    docker:
      - image: circleci/ruby:2.4
    steps:
      - checkout
      - run:
          name: Prepare Ruby environment
          command: |
            ruby --version
            echo "gem `gem --version`"
            gem update --system
            gem install bundler
            bundle install
      - run: rake test
  test-2.5:
    docker:
      - image: circleci/ruby:2.5
    steps:
      - checkout
      - run:
          name: Prepare Ruby environment
          command: |
            ruby --version
            echo "gem `gem --version`"
            gem update --system
            gem install bundler
            bundle install
      - run: rake test
  build:
    docker:
      - image: circleci/ruby:2.5
    steps:
      - checkout
      - run:
          name: Prepare Ruby environment
          command: |
            ruby --version
            echo "gem `gem --version`"
            gem update --system
            gem install bundler
            bundle install
      - run:
          name: Build Gem
          command: gem build texlogparser.gemspec
      - persist_to_workspace:
          root: .
          paths:
            - .circleci/gem_credentials
            - tex_log_parser*.gem
            - test/texlogs/*.log
  doc:
    docker:
      - image: circleci/ruby:2.5
    steps:
      - checkout
      - run:
          name: Prepare Ruby environment
          command: |
            ruby --version
            echo "gem `gem --version`"
            gem update --system
            gem install bundler
            bundle install
      - run:
          name: Build Documentation
          command: rake doc
  test-cli:
    docker:
      - image: circleci/ruby:2.5
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install Gem
          command: gem install tex_log_parser*.gem
      - run:
         name: Test version output
         command: texlogparser -v
      - run:
          name: Test an actual log
          command: texlogparser -i `ls -d1 test/texlogs/*.log | head -1`
  deploy:
    docker:
      - image: circleci/ruby:2.5
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy Gem
          command: |
            echo "gem `gem --version`"
            mkdir ~/.gem
            cat .circleci/gem_credentials | sed -e "s/__RUBYGEMS_API_KEY__/${RUBYGEMS_API_KEY}/" > ~/.gem/credentials
            chmod 0600 ~/.gem/credentials
            gem push tex_log_parser*.gem
            shred -u ~/.gem/credentials

workflows:
  version: 2
  # Only testing; run on all commits but version tags.
  test:
    jobs:
      - test-2.3:
          filters:
            tags:
              ignore: /^v.*/
      - test-2.4:
          filters:
            tags:
              ignore: /^v.*/
      - test-2.5:
          filters:
            tags:
              ignore: /^v.*/
      - doc:
          filters:
            tags:
              ignore: /^v.*/
      - build:
          requires:
            - test-2.3
            - test-2.4
            - test-2.5
          filters:
            tags:
              ignore: /^v.*/
      - test-cli:
          requires:
            - build
          filters:
            tags:
              ignore: /^v.*/
  # Testing and deployment; run all version tags only.
  test-and-deploy:
    jobs:
      - test-2.3:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - test-2.4:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - test-2.5:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - doc:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - build:
          requires:
            - test-2.3
            - test-2.4
            - test-2.5
          filters:
            filters:
              branches:
                ignore: /.*/
              tags:
                only: /^v.*/
      - test-cli:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - deploy:
          requires:
            - test-cli
            - doc
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

# Notes:
# - store_artifacts --> make Gem file downloadable from Circle
# - store_test_results --> for better test analysis